@echo off
chcp 65001 >nul
rem Устанавливает автозапуск монитора почты при входе в Windows.
rem Файл в папке автозагрузки создаётся с АБСОЛЮТНЫМ путём к этому проекту,
rem поэтому после переноса папки нужно запустить установку заново.
set "TARGET=%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup\bom_mail_monitor.bat"

> "%TARGET%" echo @echo off
>> "%TARGET%" echo rem bom-price-parser mail monitor autostart (generated by INSTALL_AUTOSTART.bat)
>> "%TARGET%" echo powershell -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "%~dp0start_mail.ps1"

if exist "%TARGET%" (
    echo.
    echo Автозапуск установлен: монитор почты будет стартовать при входе в Windows.
    echo Путь к проекту: %~dp0
    echo Удалить автозапуск: UNINSTALL_AUTOSTART.bat
) else (
    echo Не удалось создать файл автозапуска: %TARGET%
)
pause
